(function(){
'use strict';
if(window.__ACLLAR_ORDEN_ESTABLE__)return;window.__ACLLAR_ORDEN_ESTABLE__=true;
const AC=/^AC-\d{3}[A-Z]?$/i;
const cleanKey='limpieza-done';
function visible(e){const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0}
function supa(){return window.__ACLLAR_SUPABASE||window.supabaseClient||window.supabase||null}
async function appData(key){const c=supa();if(!c?.from)return null;try{const r=await c.from('acllar_app_data').select('key,value').eq('key',key).maybeSingle();if(!r.error&&r.data)return JSON.parse(r.data.value);const s=await c.from('acllar_app_data').select('key,value').eq('key','__ACLLAR_SOURCE_OF_TRUTH__').maybeSingle();if(s.error||!s.data)return null;const snap=JSON.parse(s.data.value||'{}');if(key===cleanKey)return snap.limpiezaDone||[];return null}catch{return null}}
async function storageData(key){try{if(!window.storage?.get)return null;const r=await window.storage.get(key,false);return r?.value?JSON.parse(r.value):null}catch{return null}}
function latestCleaned(v){const out={};if(!v||typeof v!=='object')return out;const entries=Array.isArray(v)?v:Object.entries(v).flatMap(([day,obj])=>obj?.cleaned?Object.entries(obj.cleaned).map(([ac])=>[ac,day]):[]);for(const item of entries){if(!Array.isArray(item)||item.length<2)continue;const ac=String(item[0]||'').split('|')[0].trim().toUpperCase();const d=String(item[1]||'').slice(0,10);if(AC.test(ac)&&/^\d{4}-\d{2}-\d{2}$/.test(d)&&(!out[ac]||d>out[ac]))out[ac]=d}return out}
function dateOfSection(h){const all=[...document.querySelectorAll('*')].filter(e=>visible(e)&&/^(Lun|Mar|Mi[eé]|Jue|Vie|S[aá]b|Dom),\s*\d{1,2}\/\d{1,2}/i.test((e.textContent||'').trim()));const hr=h.getBoundingClientRect();let best=null,top=-1e9;for(const e of all){const r=e.getBoundingClientRect();if(r.top<=hr.top&&r.top>top){best=e;top=r.top}}const m=(best?.textContent||'').match(/(\d{1,2})\/(\d{1,2})/);if(!m)return new Date().toISOString().slice(0,10);return `${new Date().getFullYear()}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`}
function sections(){const all=[...document.querySelectorAll('*')];return all.filter(e=>visible(e)&&/^A LIMPIAR\s*\(/i.test((e.textContent||'').trim())).map(h=>{const hr=h.getBoundingClientRect();let stop=Infinity;for(const e of all){if(visible(e)&&/^SALEN HOY\s*\(/i.test((e.textContent||'').trim())){const r=e.getBoundingClientRect();if(r.top>hr.bottom&&r.top<stop)stop=r.top}}const seen=new Set(),rows=[];for(const e of all){const t=(e.textContent||'').trim();if(!AC.test(t)||e.children.length||!visible(e))continue;const r=e.getBoundingClientRect();if(r.top<=hr.bottom||r.top>=stop)continue;const ac=t.toUpperCase();if(seen.has(ac))continue;seen.add(ac);rows.push({ac,el:e,row:e.parentElement})}rows.sort((a,b)=>a.el.getBoundingClientRect().top-b.el.getBoundingClientRect().top);return{h,date:dateOfSection(h),rows}}).filter(x=>x.rows.length)}
async function plan(date){const c=supa();if(!c?.from)return[];try{const r=await c.from('limpieza_plan').select('ac_id,prioridad,estado').eq('fecha',date);return r.error?[]:(r.data||[])}catch{return[]}}
function sortRows(rows,p){const pri={};for(const x of p)if(x.estado==='pendiente'&&x.prioridad!=null)pri[String(x.ac_id).toUpperCase()]=Number(x.prioridad);return rows.slice().sort((a,b)=>(pri[a.ac]??999999)-(pri[b.ac]??999999)||a.ac.localeCompare(b.ac))}
function panel(g,list){let p=document.getElementById('orden-ac-'+g.date);if(!p){p=document.createElement('div');p.id='orden-ac-'+g.date;p.style.cssText='margin:8px 0 10px;padding:10px;background:#f4f7f5;border:2px solid #15302b;border-radius:10px;color:#15302b';g.h.parentElement?.insertBefore(p,g.h.nextSibling)}p.innerHTML='<b style="font-size:14px">ORDEN DE LIMPIEZA</b><div style="font-size:11px;color:#65736e;margin:2px 0 6px">Todas las pendientes disponibles · sube o baja</div>'+list.map((x,i)=>`<div style="display:flex;align-items:center;gap:6px;border-top:1px solid #dfe6e2;padding:5px 0"><span style="width:18px;color:#7a8882;font-weight:700">${i+1}</span><b style="font-family:monospace;flex:1">${x.ac}</b><button data-up="${x.ac}" style="width:36px;height:30px">▲</button><button data-down="${x.ac}" style="width:36px;height:30px">▼</button></div>`).join('');return p}
async function save(date,list){const c=supa();if(!c?.from)return;for(let i=0;i<list.length;i++)await c.from('limpieza_plan').update({prioridad:i+1}).eq('fecha',date).eq('ac_id',list[i].ac)}
function move(g,list,ac,delta){const i=list.findIndex(x=>x.ac===ac),j=i+delta;if(i<0||j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];renderSection(g,list);save(g.date,list).then(()=>setTimeout(render,500))}
function renderSection(g,list){const p=panel(g,list);p.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(g,list,b.dataset.up,-1));p.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(g,list,b.dataset.down,1));const parent=list[0]?.row?.parentElement;if(!parent||list.some(x=>x.row.parentElement!==parent))return;let anchor=list[0].row;parent.insertBefore(anchor,parent.firstChild);for(let i=1;i<list.length;i++){parent.insertBefore(list[i].row,anchor.nextSibling);anchor=list[i].row}}
function cleanLabel(d){return 'Limpia desde '+d.slice(8,10)+'/'+d.slice(5,7)+'/'+d.slice(0,4)}
function dateCandidates(value){if(value==null)return[];const s=String(value).trim();const out=[];let m;const iso=s.match(/(20\d{2})[-\/.](\d{1,2})[-\/.](\d{1,2})/);if(iso)out.push(`${iso[1]}-${String(+iso[2]).padStart(2,'0')}-${String(+iso[3]).padStart(2,'0')}`);m=s.match(/(\d{1,2})[-\/.](\d{1,2})[-\/.](20\d{2})/);if(m)out.push(`${m[3]}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`);return out}
function rowObjects(snapshot){if(!snapshot)return[];const rows=Array.isArray(snapshot.data)?snapshot.data:[];const headers=Array.isArray(snapshot.headers)?snapshot.headers:[];const mapping=snapshot.mapping&&typeof snapshot.mapping==='object'?snapshot.mapping:{};return rows.map(row=>{if(row&&typeof row==='object'&&!Array.isArray(row))return row;const o={};headers.forEach((h,i)=>{o[String(h||'').trim()]=Array.isArray(row)?row[i]:undefined});return o}).map(row=>({row,mapping}));}
function valueBySemantic(row,mapping,aliases){const keys=Object.keys(row||{});const norm=s=>String(s||'').normalize('NFD').replace(/[\u0300-\u036f]/g,'').toLowerCase();for(const a of aliases){const na=norm(a);const mk=Object.keys(mapping||{}).find(k=>norm(k)===na||norm(k).includes(na));if(mk){const actual=mapping[mk];if(actual!=null&&row[actual]!=null&&String(row[actual]).trim()!=='')return row[actual];if(row[mk]!=null&&String(row[mk]).trim()!=='')return row[mk]}}for(const k of keys){const nk=norm(k);if(aliases.some(a=>nk.includes(norm(a)))){const v=row[k];if(v!=null&&String(v).trim()!=='')return v}}return null}
async function currentReturnDates(){const snap=await storageData('acllar-reservas-C');const out={};for(const {row,mapping} of rowObjects(snap)){const acv=valueBySemantic(row,mapping,['ac','matricula','matricula vehiculo','vehiculo','vehículo','unidad']);const acm=String(acv||'').match(/AC-\d{3}[A-Z]?/i);if(!acm)continue;const ac=acm[0].toUpperCase();const vals=[];for(const k of Object.keys(row||{})){vals.push(...dateCandidates(row[k]))}const semantic=valueBySemantic(row,mapping,['devolucion','devolución','fecha devolucion','fecha devolución','retorno','regreso','fin alquiler','hasta']);vals.push(...dateCandidates(semantic));if(!vals.length)continue;const unique=[...new Set(vals)].sort();const today=new Date().toISOString().slice(0,10);const future=unique.filter(d=>d>=today);const d=(future[0]||unique[unique.length-1]);if(d)out[ac]=d}return out}
async function patchCleanLabels(){const done=latestCleaned(await appData(cleanKey));if(!Object.keys(done).length)return;const returns=await currentReturnDates();const all=[...document.querySelectorAll('*')],heads=all.filter(e=>visible(e)&&/^SALEN HOY\s*\(/i.test((e.textContent||'').trim())).sort((a,b)=>a.getBoundingClientRect().top-b.getBoundingClientRect().top);for(const e of all){if(!visible(e)||e.children.length)continue;const t=(e.textContent||'').trim();if(!/^(Se limpia hoy|Pendiente de limpieza|Limpia desde \d{2}\/\d{2}\/\d{4})$/i.test(t))continue;const r=e.getBoundingClientRect();let h=null;for(const x of heads){const xr=x.getBoundingClientRect();if(xr.top<r.top)h=x;else break}if(!h)continue;let node=e.parentElement,ac=null;for(let n=0;n<10&&node;n++,node=node.parentElement){const m=(node.textContent||'').match(/\bAC-\d{3}[A-Z]?\b/i);if(m){ac=m[0].toUpperCase();break}}if(!ac||!done[ac])continue;const release=returns[ac]||dateOfSection(h);if(done[ac]<release)e.textContent='Se limpia hoy';else e.textContent=cleanLabel(done[ac])}}
async function render(){const gs=sections();for(const g of gs){const p=await plan(g.date);const list=sortRows(g.rows,p);renderSection(g,list)}await patchCleanLabels()}
function start(){setTimeout(render,800);setInterval(render,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
