(function(){
'use strict';
if(window.__ACLLAR_ORDEN_ESTABLE__)return;window.__ACLLAR_ORDEN_ESTABLE__=true;
const AC=/^AC-\d{3}[A-Z]?$/i;
const cleanKey='limpieza-done';
function visible(e){const s=getComputedStyle(e),r=e.getBoundingClientRect();return s.display!=='none'&&s.visibility!=='hidden'&&r.width>0&&r.height>0}
function supa(){return window.__ACLLAR_SUPABASE||window.supabaseClient||window.supabase||null}
async function appData(key){const c=supa();if(!c?.from)return null;try{const r=await c.from('acllar_app_data').select('value').eq('key',key).maybeSingle();if(r.error||!r.data)return null;return JSON.parse(r.data.value)}catch{return null}}
function latestCleaned(v){const out={};if(!v||typeof v!=='object')return out;for(const [day,obj] of Object.entries(v)){const d=String(day).slice(0,10);if(!/^\d{4}-\d{2}-\d{2}$/.test(d)||!obj?.cleaned)continue;for(const id of Object.values(obj.cleaned)){const ac=String(id||'').split('|')[0].trim().toUpperCase();if(AC.test(ac)&&(!out[ac]||d>out[ac]))out[ac]=d}}return out}
function dateOfSection(h){const all=[...document.querySelectorAll('*')].filter(e=>visible(e)&&/^(Lun|Mar|Mi[eé]|Jue|Vie|S[aá]b|Dom),\s*\d{1,2}\/\d{1,2}/i.test((e.textContent||'').trim()));const hr=h.getBoundingClientRect();let best=null,top=-1e9;for(const e of all){const r=e.getBoundingClientRect();if(r.top<=hr.top&&r.top>top){best=e;top=r.top}}const m=(best?.textContent||'').match(/(\d{1,2})\/(\d{1,2})/);if(!m)return new Date().toISOString().slice(0,10);return `${new Date().getFullYear()}-${String(+m[2]).padStart(2,'0')}-${String(+m[1]).padStart(2,'0')}`}
function sections(){const all=[...document.querySelectorAll('*')];return all.filter(e=>visible(e)&&/^A LIMPIAR\s*\(/i.test((e.textContent||'').trim())).map(h=>{const hr=h.getBoundingClientRect();let stop=Infinity;for(const e of all){if(visible(e)&&/^SALEN HOY\s*\(/i.test((e.textContent||'').trim())){const r=e.getBoundingClientRect();if(r.top>hr.bottom&&r.top<stop)stop=r.top}}const seen=new Set(),rows=[];for(const e of all){const t=(e.textContent||'').trim();if(!AC.test(t)||e.children.length||!visible(e))continue;const r=e.getBoundingClientRect();if(r.top<=hr.bottom||r.top>=stop)continue;const ac=t.toUpperCase();if(seen.has(ac))continue;seen.add(ac);rows.push({ac,el:e,row:e.parentElement})}rows.sort((a,b)=>a.el.getBoundingClientRect().top-b.el.getBoundingClientRect().top);return{h,date:dateOfSection(h),rows}}).filter(x=>x.rows.length)}
async function plan(date){const c=supa();if(!c?.from)return[];try{const r=await c.from('limpieza_plan').select('ac_id,prioridad,estado').eq('fecha',date);return r.error?[]:(r.data||[])}catch{return[]}}
function sortRows(rows,p){const pri={};for(const x of p)if(x.estado==='pendiente'&&x.prioridad!=null)pri[String(x.ac_id).toUpperCase()]=Number(x.prioridad);return rows.slice().sort((a,b)=>(pri[a.ac]??999999)-(pri[b.ac]??999999)||a.ac.localeCompare(b.ac))}
function panel(g,list){let p=document.getElementById('orden-ac-'+g.date);if(!p){p=document.createElement('div');p.id='orden-ac-'+g.date;p.style.cssText='margin:8px 0 10px;padding:10px;background:#f4f7f5;border:2px solid #15302b;border-radius:10px;color:#15302b';g.h.parentElement?.insertBefore(p,g.h.nextSibling)}p.innerHTML='<b style="font-size:14px">ORDEN DE LIMPIEZA</b><div style="font-size:11px;color:#65736e;margin:2px 0 6px">Todas las pendientes disponibles · sube o baja</div>'+list.map((x,i)=>`<div style="display:flex;align-items:center;gap:6px;border-top:1px solid #dfe6e2;padding:5px 0"><span style="width:18px;color:#7a8882;font-weight:700">${i+1}</span><b style="font-family:monospace;flex:1">${x.ac}</b><button data-up="${x.ac}" style="width:36px;height:30px">▲</button><button data-down="${x.ac}" style="width:36px;height:30px">▼</button></div>`).join('');return p}
async function save(date,list){const c=supa();if(!c?.from)return;for(let i=0;i<list.length;i++)await c.from('limpieza_plan').update({prioridad:i+1}).eq('fecha',date).eq('ac_id',list[i].ac)}
function move(g,list,ac,delta){const i=list.findIndex(x=>x.ac===ac),j=i+delta;if(i<0||j<0||j>=list.length)return;[list[i],list[j]]=[list[j],list[i]];renderSection(g,list);save(g.date,list).then(()=>setTimeout(render,500))}
function renderSection(g,list){const p=panel(g,list);p.querySelectorAll('[data-up]').forEach(b=>b.onclick=()=>move(g,list,b.dataset.up,-1));p.querySelectorAll('[data-down]').forEach(b=>b.onclick=()=>move(g,list,b.dataset.down,1));const parent=list[0]?.row?.parentElement;if(!parent||list.some(x=>x.row.parentElement!==parent))return;let anchor=list[0].row;parent.insertBefore(anchor,parent.firstChild);for(let i=1;i<list.length;i++){parent.insertBefore(list[i].row,anchor.nextSibling);anchor=list[i].row}}
async function patchCleanLabels(){const done=latestCleaned(await appData(cleanKey));if(!Object.keys(done).length)return;const all=[...document.querySelectorAll('*')];for(const e of all){if(!visible(e)||e.children.length)continue;const txt=(e.textContent||'').trim();if(txt!=='Se limpia hoy')continue;let node=e.parentElement,ac=null;for(let n=0;n<5&&node;n++,node=node.parentElement){const m=(node.textContent||'').match(/AC-\d{3}[A-Z]?/i);if(m){ac=m[0].toUpperCase();break}}if(ac&&done[ac])e.textContent='Limpia desde '+done[ac].slice(8,10)+'/'+done[ac].slice(5,7)+'/'+done[ac].slice(0,4);else e.textContent='Pendiente de limpieza'}}
async function render(){const gs=sections();for(const g of gs){const p=await plan(g.date);const list=sortRows(g.rows,p);renderSection(g,list)}await patchCleanLabels()}
function start(){setTimeout(render,800);setInterval(render,5000)}
if(document.readyState==='loading')document.addEventListener('DOMContentLoaded',start);else start();
})();
